import { db } from "./index";
import { submissionsTable, aiOutputsTable, notesTable } from "./schema";

const dummyFormData1 = {
  email: "sarah.johnson@email.com.au",
  declaration18: "I agree",
  firstName: "Sarah",
  secondName: "Johnson",
  streetAddress: "14 Ridgeback Road",
  suburbTownStatePostcode: "Bowral NSW 2576",
  phoneNumber: "0412 345 678",
  currentRiderName: "",
  listingServiceType: "1. Listing Service - commission/ Consultancy Fee due later (see terms)",
  listingServiceAdditionalInfo: "",
  additionalMarketing: ["Featured Horsezone ad $75"],
  photosVideoCommitment: "I will send this today",
  preferredSalesPrice: "$18,500 firm. Genuine buyers only.",
  salesAdvertisementDescription: "Beautiful, well educated mare, competed at state level dressage. Safe and reliable in all situations. Would suit an intermediate to capable rider looking to step up their dressage career.",
  horseName: "Riverstone Arabella",
  horseLocation: "",
  age: "9 years",
  height: "16.1hh",
  colour: "Dark bay with small star",
  gender: "Mare",
  breed: "Warmblood x Thoroughbred, Sire: Rotspon, Dam: Lady Arabesque",
  registrations: "EA registered #WB-4421",
  generalEducation: ["Well educated", "Established level of education"],
  educationAdditionalInfo: "Schooled consistently for 6 years. Trained by qualified coach weekly. Established in all three gaits, working on collection and lateral movements.",
  disciplines: ["dressage/ showing"],
  skills: ["trail riding", "leading other horses", "not worried by fireworks", "not worried by busy roads", "not concerned by farm life - tractors, trucks, motorbikes, livestock"],
  needsWorkToImprove: "Flying changes — she has the ability but needs more consistent work. Counter canter is also a work in progress.",
  minimumRiderLevel: "Intermediate Rider defined as someone who has been riding / competing regularly for at least three years, has independent hands and balanced position/ seat; can walk, trot and canter on their own horse. Rider is confident if the horse is reasonably well behaved. Prefers a schoolmaster type without any major quirks.",
  riderSuitabilityExtra: ["Would suit a young rider - 18-24 yo", "Would suit an amateur adult rider", "Would suit a mature, older rider"],
  horseRequires: ["A rider who is under regular professional instruction."],
  riderSuitabilityVariesInfo: "With an experienced rider she will work confidently. With a novice or nervous rider she can pick up on tension and become looky.",
  underSaddle: ["willing and responsive", "soft and 'light' in the bridle", "willingly collects", "tolerant of rider mistakes", "non-reactive unless something major happens", "can be looky in certain situations"],
  underSaddleAdditionalInfo: "Arabella has a lovely, elastic trot and a round, uphill canter. She can spook at flapping tarps or sudden noises but recovers quickly.",
  vicesOrQuirks: ["cold backed at the start of each ride - tense, tail swishy but DOESN'T buck, pigroot or kick out", "is 'marey'"],
  vicesAdditionalInfo: "Cold back only at the very start of a ride — once she has walked for 5 minutes she is totally fine. Can be mareish in spring when in season but never dangerous.",
  behaviourInOutOfWork: ["does not need regular riding to be reliable and safe", "needs lunging before riding after a spell"],
  fitnessLevel: "In work ridden 3 plus times a week",
  currentlyCompeting: "yes",
  competitionHistory: "Competed at state level",
  competitionHistoryAdditionalInfo: "Competed NSW State Dressage Championships 2023 at Prelim level. Multiple class wins at affiliated dressage competitions. Currently training at Novice.",
  gearTackNeeds: ["'light; and happy being ridden in a snaffle bit", "no specific tack needed"],
  gearAdditionalInfo: "",
  handlingBehaviour: ["unflappable and calm, safe and easy to manage", "easy to catch", "well mannered on the ground", "leads calmly and willingly", "ties up happily and calmly without fuss or pulling back", "self loads or loads into float/ truck very easily, stands quietly when travelling, unloads calmly", "easy and calm to clip", "reliable for the farrier/ to handle when picking out feet", "is good for the vet", "easy to wash"],
  handlingAdditionalInfo: "",
  feeding: ["horse is fed 'hard' feed"],
  feedingAdditionalInfo: "2x feeds daily — AM: 500g Mitavite Gumnuts + 200g Coolstance copra. PM: 500g Mitavite Gumnuts + lucerne chaff 500g. Meadow hay ad lib overnight. Fresh water always available.",
  medicalManagementIssues: ["no past or present medical issues", "given supplements as a 'preventative'."],
  medicalAdditionalInfo: "On daily Vitamin E and Selenium supplement as preventative. No injuries, no history of lameness. Current clean vet check June 2024.",
  management: ["can be kept in a herd situation", "management is entirely flexible"],
  managementAdditionalInfo: "Currently paddocked with 2 other mares. Happy in any management situation.",
  lastVaccinationDate: "February 2025",
  vaccinatedFor: ["Tetanus", "Strangles", "Hendra", "Equine Influenza"],
  lastDentalDate: "November 2024",
  dentalAdditionalInfo: "",
  farrier: ["shod"],
  farrierAdditionalInfo: "Shod all four feet. 6-weekly farrier appointments. No issues.",
  vetChecks: ["past vet checks available", "vet check can be done at potential buyers expense"],
  vetChecksAdditionalInfo: "",
  reasonForSale: "Seller is relocating overseas for work and cannot take Arabella. It is a heartbreaking decision.",
  idealHome: "Looking for an experienced amateur or junior competitor who will continue her dressage career and give her consistent work and attention. She loves being loved on and would thrive with a dedicated rider who trains regularly with a coach.",
  generalTermsAgreed: true,
  digitalSignatureConfirmation: "I understand the service that I have selected and confirm that I want to list the horse with PHS. To speed up the process, I will send photos and videos to 0428239317 via WhatsApp to confirm the listing - PHS will start drafting the ad and portfolio.",
  signature: "Sarah Johnson",
};

const dummyFormData2 = {
  email: "mike.harris@outlook.com",
  declaration18: "I agree",
  firstName: "Mike",
  secondName: "Harris",
  streetAddress: "223 Hinterland Drive",
  suburbTownStatePostcode: "Maleny QLD 4552",
  phoneNumber: "0487 654 321",
  currentRiderName: "Kylie Harris",
  listingServiceType: "2. Listing Service - commission paid upfront for 10% off Consultancy Fee",
  listingServiceAdditionalInfo: "Happy to pay upfront for the discount.",
  additionalMarketing: ["Horsedeals ad package from $59", "Featured Horsezone ad $75"],
  photosVideoCommitment: "I will send asap",
  preferredSalesPrice: "$32,000 negotiable for the right home.",
  salesAdvertisementDescription: "",
  horseName: "QH Captain Jack",
  horseLocation: "Maleny QLD — same as owner address",
  age: "12 years",
  height: "15.3hh",
  colour: "Palomino with flaxen mane and tail",
  gender: "Gelding",
  breed: "Quarter Horse, Sire: Hollywood Gold Bar, Dam: Miss Poco Peppy",
  registrations: "AQHA registered",
  generalEducation: ["Schoolmaster", "Superior level of education"],
  educationAdditionalInfo: "Jack has competed at the highest level of campdraft and is an absolute professional. He knows his job inside out.",
  disciplines: ["campdrafting, team penning, reining, roping etc", "pleasure/ trail riding", "mustering/ feed lot work"],
  skills: ["mustered or done cattle work", "trail riding", "hasn't mustered but is safe and quiet to ride near cattle/ sheep", "bareback", "leading other horses", "not worried by fireworks", "not worried by busy roads", "not concerned by farm life - tractors, trucks, motorbikes, livestock", "not concerned by dogs or other pets", "has visited and swum at the beach"],
  needsWorkToImprove: "",
  minimumRiderLevel: "Capable Rider defined as someone who has been riding / competing regularly for at least five years, has independent hands and balanced position/ seat; can walk, trot and canter on multiple horses both young and educated. Is confident in all situations. Can handle some quirks in horses.",
  riderSuitabilityExtra: ["Would suit a young rider - 18-24 yo", "Would suit an amateur adult rider", "Would suit a mature, older rider"],
  horseRequires: ["N/A"],
  riderSuitabilityVariesInfo: "",
  underSaddle: ["willing and responsive", "puts in as much effort as required by the rider", "adapts to the competence/ confidence level of the rider i.e. beginner safe but steps up with a more experienced rider", "tolerant of rider mistakes", "non-reactive and unflappable under saddle"],
  underSaddleAdditionalInfo: "Jack is one of those horses that truly reads his rider. In the camp he is all business. On a trail ride he plods along happily. Exceptional horse.",
  vicesOrQuirks: ["no vices or quirks"],
  vicesAdditionalInfo: "",
  behaviourInOutOfWork: ["is safe to hop straight on after a spell", "does not need regular riding to be reliable and safe"],
  fitnessLevel: "In work 5 plus times a week",
  currentlyCompeting: "yes",
  competitionHistory: "Completed and won/ placed at State level",
  competitionHistoryAdditionalInfo: "Multiple A-grade campdraft placings across QLD and NSW. Won the Open at Kilkivan and Eidsvold 2023. Consistent A-grade performer.",
  gearTackNeeds: ["specific bit i.e. pelham, kimblewick, universal, combination or gag", "this gear will be included in sale"],
  gearAdditionalInfo: "Works in a Tom Thumb snaffle for camp work. Full matching campdraft saddle, breast plate and crupper included in sale price.",
  handlingBehaviour: ["unflappable and calm, safe and easy to manage", "easy to catch", "well mannered on the ground", "leads calmly and willingly", "ties up happily and calmly without fuss or pulling back", "self loads or loads into float/ truck very easily, stands quietly when travelling, unloads calmly", "easy and calm to clip", "reliable for the farrier/ to handle when picking out feet", "is good for the vet", "easy to wash", "tolerant of handler mistakes"],
  handlingAdditionalInfo: "Jack is suitable for capable handlers. A very genuine and honest horse.",
  feeding: ["horse is fed 'hard' feed"],
  feedingAdditionalInfo: "AM: 1kg Barastoc Feeds Enduro + 500g copra + 1kg lucerne chaff. PM same. Grass pasture during day, hay overnight in stable. Condition score 4-4.5.",
  medicalManagementIssues: ["no medical issues, injuries, supplements or prescription medication.", "we have current 'clean' xrays."],
  medicalAdditionalInfo: "Clean full set of xrays taken March 2025 by Maleny Vets — available on request. No issues whatsoever.",
  management: ["can be kept in a herd situation", "can be stabled 12 hours a day/ paddocked for 12 hours a day", "management is entirely flexible"],
  managementAdditionalInfo: "Currently paddocked with one other gelding overnight and stabled during the day. Extremely adaptable.",
  lastVaccinationDate: "January 2025",
  vaccinatedFor: ["Tetanus", "Hendra", "Equine Influenza"],
  lastDentalDate: "October 2024",
  dentalAdditionalInfo: "",
  farrier: ["shod"],
  farrierAdditionalInfo: "Shod all four with plates front — 5-weekly cycle. No corrective work needed.",
  vetChecks: ["current xrays available (maximum 3 months old)", "vet check can be done at potential buyers expense"],
  vetChecksAdditionalInfo: "",
  reasonForSale: "Family is downsizing the operation. We have retired from campdraft and Jack deserves to keep competing with someone who will use him properly.",
  idealHome: "Active competitor or serious recreational rider who will keep him in consistent work. He is happiest when he has a job to do. Would suit a campdraft competitor or a serious trail/station rider.",
  generalTermsAgreed: true,
  digitalSignatureConfirmation: "I understand the service that I have selected and confirm that I want to list the horse with PHS. To speed up the process, I will send photos and videos to 0428239317 via WhatsApp to confirm the listing - PHS will start drafting the ad and portfolio.",
  signature: "Mike Harris",
};

const dummyFormData3 = {
  email: "traceypetros@gmail.com",
  declaration18: "I agree",
  firstName: "Tracey",
  secondName: "Petros",
  streetAddress: "6 Kookaburra Close",
  suburbTownStatePostcode: "Macedon VIC 3440",
  phoneNumber: "0423 111 999",
  currentRiderName: "",
  listingServiceType: "1. Listing Service - commission/ Consultancy Fee due later (see terms)",
  listingServiceAdditionalInfo: "",
  additionalMarketing: ["No additional marketing"],
  photosVideoCommitment: "I will send this today",
  preferredSalesPrice: "$8,500. Price reflects her current level and some quirks. Genuine buyers welcome.",
  salesAdvertisementDescription: "",
  horseName: "Fern Gully Missy / Missy",
  horseLocation: "",
  age: "5 years",
  height: "15.0hh",
  colour: "Grey, darkening to dapple grey",
  gender: "Mare",
  breed: "Australian Stock Horse x Thoroughbred",
  registrations: "ASHS registered",
  generalEducation: ["Basic education", "Started under saddle"],
  educationAdditionalInfo: "Missy was broken in 18 months ago and has had consistent but light work since. She is forward going and has a lovely nature but still has much to learn.",
  disciplines: ["dressage/ showing", "pony club/ adult rider club", "pleasure/ trail riding"],
  skills: ["trail riding", "leading other horses", "low level jump schooling - cavalettis/ x rails"],
  needsWorkToImprove: "Straightness and rhythm at canter. Still figuring out her balance and occasionally falls in on circles. Would benefit from consistent flatwork with a good coach.",
  minimumRiderLevel: "Capable Rider defined as someone who has been riding / competing regularly for at least five years, has independent hands and balanced position/ seat; can walk, trot and canter on multiple horses both young and educated. Is confident in all situations. Can handle some quirks in horses.",
  riderSuitabilityExtra: ["Would suit a young rider - 18-24 yo", "Would suit an amateur adult rider"],
  horseRequires: ["Further professional training.", "A rider who is under regular professional instruction."],
  riderSuitabilityVariesInfo: "Missy is suitable for a capable, calm rider who is happy to continue her education. Not suitable for nervous or beginner riders.",
  underSaddle: ["forward and sharp", "willing and responsive", "reacts to unbalanced riders or mixed 'signals'", "can be looky in certain situations", "reacts to rider nerves", "has quirks - this will be covered in the next section"],
  underSaddleAdditionalInfo: "Missy is sensitive and forward — she responds immediately to leg and can catch unbalanced riders off guard. A light touch works well.",
  vicesOrQuirks: ["cold backed at the start of each ride - tense, tail swishy but DOESN'T buck, pigroot or kick out", "spooks - jumps on the spot/ sideways or moves forward quickly", "is 'marey'", "this happens but not regularly"],
  vicesAdditionalInfo: "Cold back usually only in colder months. Spooks at new or unexpected objects — recovers within seconds. Mareish when in season (spring) but easily managed.",
  behaviourInOutOfWork: ["needs regular riding 4 plus times a week to be reliable and safe", "needs lunging before riding after a spell"],
  fitnessLevel: "In light work - ridden 1 or 2 times a week",
  currentlyCompeting: "no",
  competitionHistory: "Has been on outings to shows or clinics but hasn't competed",
  competitionHistoryAdditionalInfo: "Has attended 3 pony club rallies and 2 dressage clinics. Well received by coaches — good attitude.",
  gearTackNeeds: ["'light; and happy being ridden in a snaffle bit", "no specific tack needed"],
  gearAdditionalInfo: "",
  handlingBehaviour: ["easy to catch", "well mannered on the ground", "leads calmly and willingly", "ties up happily and calmly without fuss or pulling back", "self loads or loads into float/ truck very easily, stands quietly when travelling, unloads calmly", "easy and calm to clip", "reliable for the farrier/ to handle when picking out feet", "is good for the vet", "easy to wash"],
  handlingAdditionalInfo: "",
  feeding: ["horse is fed 'hard' feed"],
  feedingAdditionalInfo: "AM: 500g Hygain Zero + lucerne chaff 300g. PM: small hard feed same mix. Grass pasture all day. No issues with feed or weight — easy keeper.",
  medicalManagementIssues: ["no past or present medical issues"],
  medicalAdditionalInfo: "",
  management: ["can be kept in a herd situation", "must have a companion within sight"],
  managementAdditionalInfo: "Currently paddocked with two geldings. Becomes unsettled if she cannot see another horse.",
  lastVaccinationDate: "March 2025",
  vaccinatedFor: ["Tetanus", "Strangles", "Hendra"],
  lastDentalDate: "December 2024",
  dentalAdditionalInfo: "No issues noted by vet dentist.",
  farrier: ["barefoot"],
  farrierAdditionalInfo: "Excellent feet — no corrective work needed.",
  vetChecks: ["vet check can be done at potential buyers expense"],
  vetChecksAdditionalInfo: "",
  reasonForSale: "Seller has recently had a baby and does not have time to give Missy the consistent work she needs to progress. She deserves to be ridden regularly.",
  idealHome: "A capable, patient rider who ideally trains regularly with a coach and wants a project horse to bring along. Would suit a junior competitor or amateur adult looking for a partnership to develop.",
  generalTermsAgreed: true,
  digitalSignatureConfirmation: "As above, however I would also like to discuss the horse being marketed. Please note, we do not discuss marketing strategy or listing price until the horse is listed with us.",
  signature: "Tracey Petros",
};

async function seed() {
  console.log("Seeding dummy submissions...");

  const seeds = [
    {
      form: dummyFormData1,
      status: "awaiting_review" as const,
      sellerName: "Sarah Johnson",
      sellerEmail: "sarah.johnson@email.com.au",
      sellerPhone: "0412 345 678",
      horseName: "Riverstone Arabella",
      breed: "Warmblood x Thoroughbred",
      age: "9 years",
      colour: "Dark bay with small star",
      height: "16.1hh",
      sex: "Mare",
      askingPrice: "$18,500",
      location: "Bowral NSW 2576",
      discipline: "dressage/ showing",
    },
    {
      form: dummyFormData2,
      status: "approved" as const,
      sellerName: "Mike Harris",
      sellerEmail: "mike.harris@outlook.com",
      sellerPhone: "0487 654 321",
      horseName: "QH Captain Jack",
      breed: "Quarter Horse",
      age: "12 years",
      colour: "Palomino",
      height: "15.3hh",
      sex: "Gelding",
      askingPrice: "$32,000",
      location: "Maleny QLD 4552",
      discipline: "campdrafting, team penning, reining, roping etc, pleasure/ trail riding",
    },
    {
      form: dummyFormData3,
      status: "new" as const,
      sellerName: "Tracey Petros",
      sellerEmail: "traceypetros@gmail.com",
      sellerPhone: "0423 111 999",
      horseName: "Fern Gully Missy",
      breed: "Australian Stock Horse x Thoroughbred",
      age: "5 years",
      colour: "Grey (dapple)",
      height: "15.0hh",
      sex: "Mare",
      askingPrice: "$8,500",
      location: "Macedon VIC 3440",
      discipline: "dressage/ showing, pony club/ adult rider club, pleasure/ trail riding",
    },
  ];

  for (const seed of seeds) {
    const [submission] = await db
      .insert(submissionsTable)
      .values({
        formData: seed.form as Record<string, unknown>,
        status: seed.status,
        sellerName: seed.sellerName,
        sellerEmail: seed.sellerEmail,
        sellerPhone: seed.sellerPhone,
        horseName: seed.horseName,
        breed: seed.breed,
        age: seed.age,
        colour: seed.colour,
        height: seed.height,
        sex: seed.sex,
        askingPrice: seed.askingPrice,
        location: seed.location,
        discipline: seed.discipline,
      })
      .returning();

    console.log(`  Created submission: ${submission.id} — ${seed.horseName} (${seed.status})`);

    // Add a note for the approved one
    if (seed.status === "approved") {
      await db.insert(notesTable).values({
        submissionId: submission.id,
        content: "Called seller — very motivated to sell. Photos coming through WhatsApp tonight. Requesting video of canter work. Great horse, should sell quickly.",
      });
      console.log(`  Added note to ${submission.id}`);
    }

    // Add an AI output stub for the awaiting_review one
    if (seed.status === "awaiting_review") {
      await db.insert(aiOutputsTable).values({
        submissionId: submission.id,
        masterListing: `RIVERSTONE ARABELLA — Dark Bay Warmblood x Thoroughbred Mare, 9yo, 16.1hh\n\nRiverstone Arabella is a truly exceptional mare who embodies everything a dedicated dressage rider could ask for. Bred with quality and educated with patience, this 9-year-old dark bay Warmblood x Thoroughbred is a picture of elegance and rideability.\n\nCompeting consistently at affiliated dressage competitions across NSW, Arabella achieved her finest result at the NSW State Dressage Championships in 2023 at Preliminary level. She is currently training at Novice and has the natural talent and work ethic to progress further with the right partnership.\n\nUnder saddle, Arabella is a pleasure to ride. She is willing and soft in the bridle, willinglyand genuinely collects through her topline, and tolerates the occasional rider mistake with grace. Her elastic trot and round uphill canter are the hallmarks of her Warmblood breeding. She can be slightly cold-backed at the start of a ride — a five-minute walk on a loose rein has her completely settled — and can be mareish in spring, though this is entirely manageable.\n\nOn the ground she is a delight. Easy to catch, leads calmly, ties without fuss, floats without issue and clips without concern. She is currently working 3 times per week and is in excellent condition.\n\nHealthwise, Arabella is on a daily Vitamin E/Selenium supplement as a preventative measure only. She has no history of injury or illness. Past vet checks are clean and a pre-purchase vet check can be arranged at the buyer's expense.\n\nSelling only due to the owner relocating overseas — a heartbreaking decision. Arabella is looking for a committed amateur or junior competitor who will continue her dressage career with regular professional instruction.\n\nAsking $18,500 firm. Located Bowral NSW. Enquiries to PHS — 0428239317.`,
        shortListing: `RIVERSTONE ARABELLA | 9yo Dark Bay WB x TB Mare | 16.1hh | $18,500\n\nAn elegant, well-educated dressage mare with genuine competition results. State Championships competitor (Prelim), training at Novice. Willing, soft in the bridle, beautiful elastic gaits. Excellent ground manners, floats, clips, easy care. Slight cold back (resolves quickly), mareish in spring only. Needs intermediate rider with regular coaching. Relocating overseas — genuine sale. Bowral NSW.`,
        socialCaption: `Meet Riverstone Arabella — the dressage mare that does it all with elegance.\n\nThis 9-year-old dark bay Warmblood x TB has competed at NSW State Championships and is training at Novice level. Willing, soft, and with movement that turns heads in the warm-up arena.\n\nSelling only because her owner is relocating overseas. A genuinely heartbreaking decision for a very special horse.\n\n$18,500 | Bowral NSW | DM or call 0428239317 for enquiries via PHS.`,
        hashtags: "#PHSAustralia #HorseForSale #DressageHorse #WarmbloodForSale #NSWHorses #DressageMare #HorseForSaleAustralia #StateChampionships #DressageLife #EquestrianAustralia #PerformanceHorseSales #WBxTB #HorseSale #DressageCompetitor #NoviceDressage #NSWEquestrian #HorseForSaleNSW #EquestrianLife #DressageHorseForSale #HorseMarket",
        buyerSummary: "BUYER PROFILE MATCH: Intermediate to capable amateur or junior competitor with regular access to a dressage coach. Based in NSW or willing to travel. Looking to step up their competitive career on an established mare. Budget $15,000–$22,000. Not suitable for nervous or beginner riders.",
        keySellingPoints: "1. Proven competition record — NSW State Championships, multiple class wins\n2. Beautiful elastic gaits — genuine Warmblood quality\n3. Currently training Novice — clear progression pathway\n4. Excellent ground manners — easy to manage in all situations\n5. Clean health history — Vitamin E supplement only\n6. Genuine sale — owner relocating overseas\n7. Consistent, patient education over 6 years",
        generatedAt: new Date(),
      });
      console.log(`  Added AI output to ${submission.id}`);
    }
  }

  console.log("Seeding complete.");
  process.exit(0);
}

seed().catch((e) => {
  console.error(e);
  process.exit(1);
});
